spring:
  application:
    name: mvc-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
server:
  port: 9093
  servlet:
    context-path: /${project.artifactId}