spring:
  application:
    name: mvc-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_info
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
    #数据库连接配置

server:
  port: 8002
  servlet:
    #    context-path: /${project.artifactId}
    context-path: /mvc
