eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
server:
#  enable-self-preservation: 'false #关闭保护模式'
  port: 8761
spring:
  application:
    name: @project.artifactId@
