spring:
  profiles:
    include: @app.profile@
  application:
    name: @artifactId@

server:
  port: 8004
  servlet:
    context-path: /@artifactId@

eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka

mybatis-plus:
  configuration:
    #打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

