spring:
  application:
    name: user-server
    #数据库连接配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devops
    username: root
    password: root
#  main:
#    allow-bean-definition-overriding: true

server:
  port: 8004
  servlet:
    context-path: /user

eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka

mybatis-plus:
  configuration:
    #打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

