spring:
  application:
    name: @project.artifactId@

server:
  port: 8002
  servlet:
    context-path: /@project.artifactId@

eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000



