spring:
  application:
    name: login-service
  redis:
    database: 0
    host: 172.16.24.3
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000
server:
  port: 8084
  servlet:
    context-path: /login
eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka
