spring:
  application:
    name: login
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000
server:
  port: 8083
  servlet:
    context-path: /login