eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
server:
  port: 8769
spring:
  application:
    name: service-zuul
  cloud:
    gateway:
      routes:
#        - id: userinfo-server
#          uri: http://localhost:8761/
#          predicates:
#            - Path=/userinfo/**
#          filters:
#            - StripPrefix= 1 #过滤几个前缀/为间隔
        - id: xujin_route
          uri: http://baidu.com:80/
          predicates:
          - Path=/xujin

