eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
server:
  port: 8769
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: shuai
          uri: https://www.baidu.com
          predicates:
            - Path=/shuai/**
        - id: hehe
          uri: lb://userinfo-server
          predicates:
            - Path=/product/**
#          filters:
#            - StripPrefix= 1 #过滤几个前缀/为间隔



#server:
#  port: 8888
#
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: dalaoyang
#          uri: http://www.dalaoyang.cn/
#          predicates:
#            - Path=/dalaoyang/**
#        - id: juejin
#          uri: https://juejin.im/user/5aa50b96f265da23866f836e
#          predicates:
#            - Path=/juejin/**
#        - id: shuai
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/shuai/**


