spring:
  profiles:
    include: @app.profile@
  application:
    name: @artifactId@
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8005
  servlet:
    context-path: /@artifactId@

eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka




