spring:
  profiles:
    include: @app.profile@
  application:
    name: @artifactId@

server:
  port: 8006
  servlet:
    context-path: /@artifactId@

eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
