spring:
  application:
    name: userinfo-server
    #数据库连接配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_info
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090
  servlet:
    context-path: /product

eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka


#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.provider.userinfo.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

