spring:
  profiles:
    include: @app.profile@
  application:
    name: @project.artifactId@
server:
  port: 8003
  servlet:
    context-path: /@project.artifactId@
eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #建立连接所用的时间，使用户网络状况正常的情况下，两端连接所用的时间9（单位毫秒）
  ReadTimeout: 60000
  #建立连接后从服务器取到可用资源所用的时间（单位毫秒）
  ConnectTimeout: 60000

