spring:
  application:
    name: login-server
server:
  port: 8003
  servlet:
    context-path: /login
eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka
